package Hibernate;
// Generated 11-nov-2020 11:25:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idCliente;
     private String nombreCliente;
     private String cifnif;
     private String direccionFacturacion;
     private Set envioses = new HashSet(0);
     private Set destinatarioses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String nombreCliente, String cifnif, String direccionFacturacion) {
        this.nombreCliente = nombreCliente;
        this.cifnif = cifnif;
        this.direccionFacturacion = direccionFacturacion;
    }
    public Clientes(String nombreCliente, String cifnif, String direccionFacturacion, Set envioses, Set destinatarioses) {
       this.nombreCliente = nombreCliente;
       this.cifnif = cifnif;
       this.direccionFacturacion = direccionFacturacion;
       this.envioses = envioses;
       this.destinatarioses = destinatarioses;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getCifnif() {
        return this.cifnif;
    }
    
    public void setCifnif(String cifnif) {
        this.cifnif = cifnif;
    }
    public String getDireccionFacturacion() {
        return this.direccionFacturacion;
    }
    
    public void setDireccionFacturacion(String direccionFacturacion) {
        this.direccionFacturacion = direccionFacturacion;
    }
    public Set getEnvioses() {
        return this.envioses;
    }
    
    public void setEnvioses(Set envioses) {
        this.envioses = envioses;
    }
    public Set getDestinatarioses() {
        return this.destinatarioses;
    }
    
    public void setDestinatarioses(Set destinatarioses) {
        this.destinatarioses = destinatarioses;
    }




}


