package Hibernate;
// Generated 11-nov-2020 11:25:07 by Hibernate Tools 4.3.1



/**
 * Destinatarios generated by hbm2java
 */
public class Destinatarios  implements java.io.Serializable {


     private Integer idDestinatario;
     private Clientes clientes;
     private String nombreDestinatario;
     private String dninif;
     private String codigoPostal;
     private String direccionCompleta;

    public Destinatarios() {
    }

	
    public Destinatarios(Clientes clientes, String nombreDestinatario, String codigoPostal, String direccionCompleta) {
        this.clientes = clientes;
        this.nombreDestinatario = nombreDestinatario;
        this.codigoPostal = codigoPostal;
        this.direccionCompleta = direccionCompleta;
    }
    public Destinatarios(Clientes clientes, String nombreDestinatario, String dninif, String codigoPostal, String direccionCompleta) {
       this.clientes = clientes;
       this.nombreDestinatario = nombreDestinatario;
       this.dninif = dninif;
       this.codigoPostal = codigoPostal;
       this.direccionCompleta = direccionCompleta;
    }
   
    public Integer getIdDestinatario() {
        return this.idDestinatario;
    }
    
    public void setIdDestinatario(Integer idDestinatario) {
        this.idDestinatario = idDestinatario;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getNombreDestinatario() {
        return this.nombreDestinatario;
    }
    
    public void setNombreDestinatario(String nombreDestinatario) {
        this.nombreDestinatario = nombreDestinatario;
    }
    public String getDninif() {
        return this.dninif;
    }
    
    public void setDninif(String dninif) {
        this.dninif = dninif;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getDireccionCompleta() {
        return this.direccionCompleta;
    }
    
    public void setDireccionCompleta(String direccionCompleta) {
        this.direccionCompleta = direccionCompleta;
    }




}


