package Hibernate;
// Generated 11-nov-2020 11:25:07 by Hibernate Tools 4.3.1



/**
 * Envios generated by hbm2java
 */
public class Envios  implements java.io.Serializable {


     private Integer idEnvio;
     private Clientes clientes;
     private String nombreDestinatario;
     private String dninif;
     private String codigoPostal;
     private String direccionCompleta;
     private String estadoEnvio;
     private int numIntentosEntrega;

    public Envios() {
    }

	
    public Envios(Clientes clientes, String nombreDestinatario, String codigoPostal, String direccionCompleta, String estadoEnvio, int numIntentosEntrega) {
        this.clientes = clientes;
        this.nombreDestinatario = nombreDestinatario;
        this.codigoPostal = codigoPostal;
        this.direccionCompleta = direccionCompleta;
        this.estadoEnvio = estadoEnvio;
        this.numIntentosEntrega = numIntentosEntrega;
    }
    public Envios(Clientes clientes, String nombreDestinatario, String dninif, String codigoPostal, String direccionCompleta, String estadoEnvio, int numIntentosEntrega) {
       this.clientes = clientes;
       this.nombreDestinatario = nombreDestinatario;
       this.dninif = dninif;
       this.codigoPostal = codigoPostal;
       this.direccionCompleta = direccionCompleta;
       this.estadoEnvio = estadoEnvio;
       this.numIntentosEntrega = numIntentosEntrega;
    }
   
    public Integer getIdEnvio() {
        return this.idEnvio;
    }
    
    public void setIdEnvio(Integer idEnvio) {
        this.idEnvio = idEnvio;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getNombreDestinatario() {
        return this.nombreDestinatario;
    }
    
    public void setNombreDestinatario(String nombreDestinatario) {
        this.nombreDestinatario = nombreDestinatario;
    }
    public String getDninif() {
        return this.dninif;
    }
    
    public void setDninif(String dninif) {
        this.dninif = dninif;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getDireccionCompleta() {
        return this.direccionCompleta;
    }
    
    public void setDireccionCompleta(String direccionCompleta) {
        this.direccionCompleta = direccionCompleta;
    }
    public String getEstadoEnvio() {
        return this.estadoEnvio;
    }
    
    public void setEstadoEnvio(String estadoEnvio) {
        this.estadoEnvio = estadoEnvio;
    }
    public int getNumIntentosEntrega() {
        return this.numIntentosEntrega;
    }
    
    public void setNumIntentosEntrega(int numIntentosEntrega) {
        this.numIntentosEntrega = numIntentosEntrega;
    }




}


