package Hibernate;
// Generated 11-nov-2020 11:25:07 by Hibernate Tools 4.3.1



/**
 * Inform�tica generated by hbm2java
 */
public class Informatica  implements java.io.Serializable {


     private Integer idArticulo;
     private String articulo;
     private Integer NDeArticulos;
     private Integer precioArticulo;

    public Informatica() {
    }

    public Informatica(String articulo, Integer NDeArticulos, Integer precioArticulo) {
       this.articulo = articulo;
       this.NDeArticulos = NDeArticulos;
       this.precioArticulo = precioArticulo;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(String articulo) {
        this.articulo = articulo;
    }
    public Integer getNDeArticulos() {
        return this.NDeArticulos;
    }
    
    public void setNDeArticulos(Integer NDeArticulos) {
        this.NDeArticulos = NDeArticulos;
    }
    public Integer getPrecioArticulo() {
        return this.precioArticulo;
    }
    
    public void setPrecioArticulo(Integer precioArticulo) {
        this.precioArticulo = precioArticulo;
    }




}


